Traceback (most recent call last):
  File "/Users/buckleywiley/Projects/GTXR internship/GTXR-Antenna-Tracker/calculator.py", line 557, in OnInputChange
    self.update_calculations()
  File "/Users/buckleywiley/Projects/GTXR internship/GTXR-Antenna-Tracker/calculator.py", line 545, in update_calculations
    self.ser.write(Altitude_bytes)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/serial/serialposix.py", line 615, in write
    raise PortNotOpenError()
serial.serialutil.PortNotOpenError: Attempting to use a port that is not open
{'lat': 0.0, 'lon': 0.0, 'elv': 0.0}
{'lat': 32.0, 'lon': 32.0, 'elv': 4343.0}
Results:
Distance: 2961.871 miles
Azimuth: 40.4895°
Altitude: -22.0024°
Traceback (most recent call last):
  File "/Users/buckleywiley/Projects/GTXR internship/GTXR-Antenna-Tracker/calculator.py", line 557, in OnInputChange
    self.update_calculations()
  File "/Users/buckleywiley/Projects/GTXR internship/GTXR-Antenna-Tracker/calculator.py", line 545, in update_calculations
    self.ser.write(Altitude_bytes)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/serial/serialposix.py", line 615, in write
    raise PortNotOpenError()
serial.serialutil.PortNotOpenError: Attempting to use a port that is not open
Opened Serial Port (Featherweight GPS): /dev/cu.Bluetooth-Incoming-Port
Selected Serial Port (Featherweight GPS): /dev/cu.Bluetooth-Incoming-Port
1: Serial Port: /dev/cu.Bluetooth-Incoming-Port, Description: n/a
Traceback (most recent call last):
  File "/Users/buckleywiley/Projects/GTXR internship/GTXR-Antenna-Tracker/calculator.py", line 450, in rescan_serial_ports
    self.serial_port_choice.Clear()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Example' object has no attribute 'serial_port_choice'
1: Serial Port: /dev/cu.Bluetooth-Incoming-Port, Description: n/a
Traceback (most recent call last):
  File "/Users/buckleywiley/Projects/GTXR internship/GTXR-Antenna-Tracker/calculator.py", line 450, in rescan_serial_ports
    self.serial_port_choice.Clear()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Example' object has no attribute 'serial_port_choice'
1: Serial Port: /dev/cu.Bluetooth-Incoming-Port, Description: n/a
Traceback (most recent call last):
  File "/Users/buckleywiley/Projects/GTXR internship/GTXR-Antenna-Tracker/calculator.py", line 450, in rescan_serial_ports
    self.serial_port_choice.Clear()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Example' object has no attribute 'serial_port_choice'
1: Serial Port: /dev/cu.Bluetooth-Incoming-Port, Description: n/a
Traceback (most recent call last):
  File "/Users/buckleywiley/Projects/GTXR internship/GTXR-Antenna-Tracker/calculator.py", line 450, in rescan_serial_ports
    self.serial_port_choice.Clear()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Example' object has no attribute 'serial_port_choice'